### ISSUE TITLE
Import items from rxjs specifically for tree shaking

### ISSUE THREAD

**Issue by PeterStaev** [wnabil/ngx-notification-bar#1]
Would be nice to have all `rxjs` items imported specifically in order to support webpack treeshaking. Here is more info from rxjs readme: https://github.com/ReactiveX/rxjs#installation-and-usage

**Comment by wnabil** [comment]
Hi, I know how to use the RXJS but i'm not sure if i understands you well.
I think you want me to use the Observers and remove the old subscription style ?

**Comment by PeterStaev** [comment]
My idea is about this code (for example) here:
https://github.com/wnabil/ngx-notification-bar/blob/46af760317d734d79f2232cd9e666acee790a014/src/notification-bar.component.ts#L9

From what I know when you import things like that this includes tons of other things that might not be used and thus could potentially increase the bundle size of the application. So the best way to import is:
```ts
import { Subscription } from 'rxjs/Subscription';
```

I could be wrong though 😄

**Comment by wnabil** [comment]
Oh yeah got it, Actually it is from the old repo not my code, i will do it and push a new update soon
Thank you for helping.

**Comment by PeterStaev** [comment]
Thanks for your work! 👍
