### ISSUE TITLE
Can't close

### ISSUE THREAD

**Issue by MilanObrenovic** [wnabil/ngx-notification-bar#17]
We only have a function to create the alert banner, can we have a function to manually close it?

**Comment by wnabil** [comment]
if you mean from the ts file using the service then no but i will add support soon
however you can add in the options allowClose option 
https://github.com/wnabil/ngx-notification-bar/blob/2ce249e2c9016cf112b5b1820ab96f60e5502f1b/projects/ngx-notification-bar/src/lib/notification-bar.component.ts#L109

**Comment by wnabil** [comment]
added in 1.12.1
