### ISSUE TITLE
Multiple Notification Bars

### ISSUE THREAD

**Issue by ntrpnr** [wnabil/ngx-notification-bar#4]
Is it possible to use multiple notification bars in the same Angular app, and choose which one that should be shown?

We would like to use the notification bar in a Bootstrap modal, and currently, both our notification bars are triggered on create.

**Comment by wnabil** [comment]
Yes it is possible but i do not think it need modification in the package, just create a service have property for example to select which target you want to use and use ngif to hide the other tag if it doesn't match the one you want to display.

if it's not clear to you i can make an example next week and put the link for you here.

**Comment by ntrpnr** [comment]
Thanks. I will let you know if we fail to do it following your instructions.
