### ISSUE TITLE
How to restrict Duplicates

### ISSUE THREAD

**Issue by xts-velkumars** [wnabil/ngx-notification-bar#7]
@wnabil 

How to restrict duplicate notifications.

is there any flag to prevent that?

**Comment by wnabil** [comment]
At the package level this is not possible but you can make a custom service and push the displayed messages in an array then check for this message before creating new one.

it should look like this

```javascript
const message = 'test notification';
if(this.customService.currentNotifications.indexOf(message) === -1) {
  this.notificationBarService.create({ message: message, type: NotificationType.Success});
  this.customService.currentNotifications.push(message);
}

```

**Comment by xts-velkumars** [comment]
good work around, thank you
